# Chapter 12

- Tensorflow Python API
```text
┌─────────────────┐               ┌────────────────┐
│tf.keras         │High-level     │tf.distribute   │
│tf.estimator     │API            │tf.saved_model  │
└─────────────────┘               │tf.autograph    │
                                  │tf.graph_util   │Deployment &
┌─────────────────┐               │tf.lite         │optimization
│tf.nn            │               │tf.quantization │
│tf.losses        │               │tf.tpu          │
│tf.metrics       │Low-level      │tf.xla          │
│tf.optimizers    │API            └────────────────┘
│tf.train         │
│tf.initializers  │               ┌────────────────┐
└─────────────────┘               │tf.lookup       │
                                  │tf.nest         │
┌─────────────────┐               │tf.ragged       │Special data
│tf.GradientTape  │Autodiff       │tf.sets         │structures
│tf.gradients()   │               │tf.sparse       │
└─────────────────┘               │tf.strings      │
                                  └────────────────┘
┌─────────────────┐
│tf.data          │               ┌────────────────┐
│tf.feature_column│               │tf.math         │
│tf.audio         │I/O &          │tf.linalg       │Math
│tf.image         │Preprocessing  │tf.signal       │
│tf.io            │               │tf.random       │
│tf.queue         │               │tf.bitwise      │
└─────────────────┘               └────────────────┘

┌─────────────────┐               ┌────────────────┐
│tf.summary       │Tensorboard    │tf.compat       │Miscellaneous
└─────────────────┘               │tf.config       │
                                  └────────────────┘
```

In [21]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

## Tensor operations

In [18]:
# define scaler
print(tf.constant(42))

# define matrix
print("\n", tf.constant([[1,2,3], [4,5,6]]))

# shape and dtype 
t = tf.constant([[1,2,3], [4,5,6]])
print("\n", (t.shape, t.dtype))

# tensor indexing
print("\n", t[:, 1], "\n" ,t[:, 1, tf.newaxis])

tf.Tensor(42, shape=(), dtype=int32)

 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

 (TensorShape([2, 3]), tf.int32)

 tf.Tensor([2 5], shape=(2,), dtype=int32) 
 tf.Tensor(
[[2]
 [5]], shape=(2, 1), dtype=int32)


In [20]:
#  ┌─ "+" calls the tf.add method
(t + 10, tf.square(t), t @ tf.transpose(t))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[11, 12, 13],
        [14, 15, 16]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 1,  4,  9],
        [16, 25, 36]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[14, 32],
        [32, 77]], dtype=int32)>)

`tf.transpose()` is different from numpy `.T` attribute: `tf` creates a new tensor with the transposed data, while `numpy` `.T` attribute is only a **view** of the transposed data. 

`keras.backend` provides interface to call corresponding tensorflow ops. 

In [24]:
# from numpy array to tf tensor
a = np.array([1,2,3])
print(tf.constant(a))

# from tf tensor to numpy array
print(t.numpy())

tf.Tensor([1 2 3], shape=(3,), dtype=int64)
[[1 2 3]
 [4 5 6]]
